apiVersion: v1
kind: ConfigMap
metadata:
  name: nexa-env
  namespace: nexa
data:
  APP_ENV: production
  LOG_LEVEL: warning
  PROMETHEUS_METRICS_ENABLED: "true"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.nexa.svc:4318/v1/traces
  AUTH_SERVICE_URL: http://auth-service:8001
  USER_SERVICE_URL: http://user-service:8002
  CONTACT_SERVICE_URL: http://contact-service:8003
  CHAT_SERVICE_URL: http://chat-service:8004
  MEDIA_SERVICE_URL: http://media-service:8005
