/**
 * Feature availability — mirrors docs/nexa/FEATURES.md
 * Use for UI gates until backend is fully wired.
 */
export const features = {
  auth: {
    register: true,
    login: true,
    logout: true,
    refresh: true,
    sessions: true,
    qrLogin: false,
    emailVerification: false,
    oauth: false,
    /** Web: password / 2FA — QR and verify-email UI off; biometrics for native apps */
    webauthn: false,
  },
  profile: {
    username: true,
    search: true,
    avatar: false,
    bio: true,
    presence: true,
  },
  chat: {
    realtime: true,
    websocket: true,
    receipts: true,
    typing: true,
    presence: true,
    optimistic: true,
    offlineSync: true,
    notifications: true,
    reactions: true,
    replies: true,
    forwards: true,
    pins: true,
    edit: true,
    delete: true,
    groups: true,
    channels: true,
    search: true,
    stickers: true,
    polls: false,
    markdown: true,
    linkPreview: true,
    mentions: true,
    hashtags: true,
    scheduled: false,
    silent: true,
    spoilers: true,
    quizzes: false,
  },
  calls: true,
  stories: false,
  bots: false,
  ai: true,
  i18n: false,
} as const;
